spring:
  data:
    mongodb:
      uri: mongodb://172.17.12.61:27018/admin
      password: Onceas2019
      username: admin
logging:
#  path: E:\\codes writing
  file: clusterdata-java.log
debug: false
#      password: guest
#      username: guest